name: Pylint and ESLint Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pylint
        run: pylint $(git ls-files '*.py' || echo "No Python files found")

  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm install; else echo "No package.json found"; fi
          npm install eslint || true

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx || echo "ESLint completed with warnings"
